---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: openwisp-postgresql
spec:
  storageClassName: nfs-provisioner
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
  storageClassName: nfs-provisioner
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: openwisp-postgresql
spec:
  storageClassName: nfs-provisioner
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: controller-pv-volume
  labels:
    type: local
    app: openwisp-controller
spec:
  storageClassName: nfs-provisioner
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/openwisp/media"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: controller-pv-claim
  labels:
    app: openwisp-controller
spec:
  storageClassName: nfs-provisioner
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: static-pv-volume
spec:
  storageClassName: nfs-provisioner
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/openwisp/static"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-pv-claim
spec:
  storageClassName: nfs-provisioner
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
